<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DKDRSK0" failures="1" tests="6" name="listenersample.RetryListener" time="0.028" errors="0" timestamp="2025-10-03T15:34:12 IST" skipped="5">
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.001">
    <skipped/>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.003">
    <skipped/>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.002">
    <skipped/>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.017">
    <skipped/>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.002">
    <skipped/>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
  <testcase classname="listenersample.RetryListener" name="createinvoicetest" time="0.003">
    <failure message="expected [login] but found [ ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [login] but found [ ]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at listenersample.RetryListener.createinvoicetest(RetryListener.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:261)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- createinvoicetest -->
  <system-out/>
</testsuite> <!-- listenersample.RetryListener -->
